# Generated by Django 3.0.6 on 2020-07-03 03:48

from django.db import migrations, models
import django.db.models.deletion
import libros.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('indice', models.IntegerField()),
                ('texto', models.FileField(upload_to='', validators=[libros.models.validatePDF])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('fecha_lanzamiento_basico', models.DateField(null=True, validators=[libros.models.validateDate])),
                ('fecha_lanzamiento_premium', models.DateField(null=True, validators=[libros.models.validateDate])),
                ('fecha_vencimiento_basico', models.DateField(blank=True, null=True, validators=[libros.models.validateDate])),
                ('fecha_vencimiento_premium', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('spoiler', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'editoriales',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.BigIntegerField(unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('sinopsis', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lanzamiento_basico', models.DateField(blank=True, null=True)),
                ('fecha_lanzamiento_premium', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento_basico', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento_premium', models.DateField(blank=True, null=True)),
                ('cantidad_partes', models.IntegerField(default=1, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='', validators=[libros.models.validatePDF])),
                ('imagen', models.ImageField(default='no_load.jpg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'libros',
            },
        ),
        migrations.CreateModel(
            name='LibroLeido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.IntegerField(default=0)),
                ('ultima_fecha', models.DateField(auto_now=True)),
                ('terminado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibroSugerido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugerencia', libros.models.LibroMinuscula(blank=True, max_length=40)),
            ],
            options={
                'verbose_name_plural': 'librosugerido',
            },
        ),
        migrations.CreateModel(
            name='ReporteOfensivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'reportes de comentarios ofensivos',
            },
        ),
        migrations.CreateModel(
            name='ReporteSpoiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Comentario')),
            ],
            options={
                'verbose_name_plural': 'reportes de spoilers',
            },
        ),
    ]
