# Generated by Django 3.0.6 on 2020-07-03 03:48

from django.db import migrations, models
import django.db.models.deletion
import libros.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0002_auto_20200703_0348'),
        ('perfiles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='exclusividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Membresia'),
        ),
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.ManyToManyField(to='libros.Genero'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libros.Libro'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfiles.Perfil'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='valor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libros.Calificacion'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='exclusividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Membresia'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libro', validators=[libros.models.validateDivision]),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libro'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.Perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='libroleido',
            unique_together={('perfil', 'libro'), ('perfil', 'cap')},
        ),
        migrations.AlterUniqueTogether(
            name='capitulo',
            unique_together={('libro', 'indice'), ('libro', 'titulo')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('libro', 'perfil')},
        ),
    ]
