# Generated by Django 3.0.6 on 2020-07-03 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fechaLanzamiento', models.DateField()),
                ('fechaExpiracion', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('descripcion_imagen', models.CharField(blank=True, max_length=1000, null=True)),
                ('trailer', models.CharField(blank=True, help_text='Nota: Utilice el formato http://www.tupagina.com/ para asignar una url externa al sitio.', max_length=50, null=True)),
                ('libro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libros.Libro')),
            ],
            options={
                'verbose_name_plural': 'novedades',
            },
        ),
    ]
